"""Registry of Czech laws for legal qualification."""

# Each law: sbirkove_cislo, nazev, typ, oblasti
# typ: "TZ" (trestní zákoník), "prestupkovy" (přestupkové zákony), "specialni" (speciální zákony)
LAW_REGISTRY: list[dict] = [
    # ── Trestní zákoník ──
    {
        "sbirkove_cislo": "40/2009",
        "nazev": "Trestní zákoník",
        "typ": "TZ",
        "oblasti": ["majetkové TČ", "násilné TČ", "hospodářské TČ", "obecně nebezpečné TČ"],
    },
    # ── Trestní řád (pro reference) ──
    {
        "sbirkove_cislo": "141/1961",
        "nazev": "Trestní řád",
        "typ": "TZ",
        "oblasti": ["trestní řízení"],
    },
    # ── Přestupkové zákony ──
    {
        "sbirkove_cislo": "251/2016",
        "nazev": "Zákon o přestupcích",
        "typ": "prestupkovy",
        "oblasti": ["obecná úprava přestupků"],
    },
    {
        "sbirkove_cislo": "250/2016",
        "nazev": "Zákon o odpovědnosti za přestupky a řízení o nich",
        "typ": "prestupkovy",
        "oblasti": ["řízení o přestupcích"],
    },
    # ── Speciální zákony ──
    {
        "sbirkove_cislo": "361/2000",
        "nazev": "Zákon o provozu na pozemních komunikacích",
        "typ": "specialni",
        "oblasti": ["dopravní přestupky", "silniční provoz"],
    },
    {
        "sbirkove_cislo": "119/2002",
        "nazev": "Zákon o střelných zbraních a střelivu",
        "typ": "specialni",
        "oblasti": ["zbraně", "střelivo"],
    },
    {
        "sbirkove_cislo": "167/1998",
        "nazev": "Zákon o návykových látkách",
        "typ": "specialni",
        "oblasti": ["drogy", "návykové látky"],
    },
    {
        "sbirkove_cislo": "65/2017",
        "nazev": "Zákon o ochraně zdraví před škodlivými účinky návykových látek",
        "typ": "specialni",
        "oblasti": ["alkohol", "tabák", "návykové látky"],
    },
    {
        "sbirkove_cislo": "262/2006",
        "nazev": "Zákoník práce",
        "typ": "specialni",
        "oblasti": ["pracovní právo", "pracovní úrazy"],
    },
    {
        "sbirkove_cislo": "89/2012",
        "nazev": "Občanský zákoník",
        "typ": "specialni",
        "oblasti": ["občanské právo", "náhrada škody"],
    },
    {
        "sbirkove_cislo": "634/1992",
        "nazev": "Zákon o ochraně spotřebitele",
        "typ": "specialni",
        "oblasti": ["ochrana spotřebitele", "nekalé obchodní praktiky"],
    },
    {
        "sbirkove_cislo": "17/1992",
        "nazev": "Zákon o životním prostředí",
        "typ": "specialni",
        "oblasti": ["životní prostředí"],
    },
    {
        "sbirkove_cislo": "114/1992",
        "nazev": "Zákon o ochraně přírody a krajiny",
        "typ": "specialni",
        "oblasti": ["ochrana přírody", "chráněná území"],
    },
    {
        "sbirkove_cislo": "541/2020",
        "nazev": "Zákon o odpadech",
        "typ": "specialni",
        "oblasti": ["odpady", "životní prostředí"],
    },
    {
        "sbirkove_cislo": "254/2001",
        "nazev": "Vodní zákon",
        "typ": "specialni",
        "oblasti": ["vodní hospodářství", "znečištění vod"],
    },
    {
        "sbirkove_cislo": "201/2012",
        "nazev": "Zákon o ochraně ovzduší",
        "typ": "specialni",
        "oblasti": ["ochrana ovzduší", "emise"],
    },
    {
        "sbirkove_cislo": "246/1992",
        "nazev": "Zákon na ochranu zvířat proti týrání",
        "typ": "specialni",
        "oblasti": ["ochrana zvířat", "týrání zvířat"],
    },
    {
        "sbirkove_cislo": "449/2001",
        "nazev": "Zákon o myslivosti",
        "typ": "specialni",
        "oblasti": ["myslivost", "pytláctví"],
    },
    {
        "sbirkove_cislo": "99/2004",
        "nazev": "Zákon o rybářství",
        "typ": "specialni",
        "oblasti": ["rybářství"],
    },
    {
        "sbirkove_cislo": "289/1995",
        "nazev": "Lesní zákon",
        "typ": "specialni",
        "oblasti": ["lesy", "lesní hospodářství"],
    },
    {
        "sbirkove_cislo": "200/1990",
        "nazev": "Zákon o přestupcích (starý)",
        "typ": "prestupkovy",
        "oblasti": ["přestupky (historický)"],
    },
    {
        "sbirkove_cislo": "326/1999",
        "nazev": "Zákon o pobytu cizinců",
        "typ": "specialni",
        "oblasti": ["cizinecké právo", "migrace"],
    },
    {
        "sbirkove_cislo": "325/1999",
        "nazev": "Zákon o azylu",
        "typ": "specialni",
        "oblasti": ["azylové právo"],
    },
    {
        "sbirkove_cislo": "586/1992",
        "nazev": "Zákon o daních z příjmů",
        "typ": "specialni",
        "oblasti": ["daně", "daňové úniky"],
    },
    {
        "sbirkove_cislo": "235/2004",
        "nazev": "Zákon o dani z přidané hodnoty",
        "typ": "specialni",
        "oblasti": ["DPH", "daňové podvody"],
    },
    {
        "sbirkove_cislo": "280/2009",
        "nazev": "Daňový řád",
        "typ": "specialni",
        "oblasti": ["daňové řízení"],
    },
    {
        "sbirkove_cislo": "253/2008",
        "nazev": "Zákon o praní špinavých peněz (AML)",
        "typ": "specialni",
        "oblasti": ["praní peněz", "financování terorismu"],
    },
    {
        "sbirkove_cislo": "418/2011",
        "nazev": "Zákon o trestní odpovědnosti právnických osob",
        "typ": "TZ",
        "oblasti": ["trestní odpovědnost právnických osob"],
    },
    {
        "sbirkove_cislo": "218/2003",
        "nazev": "Zákon o soudnictví ve věcech mládeže",
        "typ": "TZ",
        "oblasti": ["mladiství pachatelé"],
    },
    {
        "sbirkove_cislo": "273/2008",
        "nazev": "Zákon o Policii ČR",
        "typ": "specialni",
        "oblasti": ["policie", "pravomoci policie"],
    },
    {
        "sbirkove_cislo": "553/1991",
        "nazev": "Zákon o obecní policii",
        "typ": "specialni",
        "oblasti": ["obecní policie"],
    },
    {
        "sbirkove_cislo": "455/1991",
        "nazev": "Živnostenský zákon",
        "typ": "specialni",
        "oblasti": ["podnikání", "živnosti"],
    },
    {
        "sbirkove_cislo": "90/2012",
        "nazev": "Zákon o obchodních korporacích",
        "typ": "specialni",
        "oblasti": ["obchodní právo", "korporace"],
    },
    {
        "sbirkove_cislo": "256/2004",
        "nazev": "Zákon o podnikání na kapitálovém trhu",
        "typ": "specialni",
        "oblasti": ["kapitálový trh", "cenné papíry"],
    },
    {
        "sbirkove_cislo": "21/1992",
        "nazev": "Zákon o bankách",
        "typ": "specialni",
        "oblasti": ["bankovnictví"],
    },
    {
        "sbirkove_cislo": "110/2019",
        "nazev": "Zákon o zpracování osobních údajů",
        "typ": "specialni",
        "oblasti": ["GDPR", "ochrana osobních údajů"],
    },
    {
        "sbirkove_cislo": "127/2005",
        "nazev": "Zákon o elektronických komunikacích",
        "typ": "specialni",
        "oblasti": ["telekomunikace", "kybernetická bezpečnost"],
    },
    {
        "sbirkove_cislo": "181/2014",
        "nazev": "Zákon o kybernetické bezpečnosti",
        "typ": "specialni",
        "oblasti": ["kybernetická bezpečnost"],
    },
    {
        "sbirkove_cislo": "121/2000",
        "nazev": "Autorský zákon",
        "typ": "specialni",
        "oblasti": ["autorské právo", "duševní vlastnictví"],
    },
    {
        "sbirkove_cislo": "13/1993",
        "nazev": "Celní zákon",
        "typ": "specialni",
        "oblasti": ["celní řízení", "pašování"],
    },
    {
        "sbirkove_cislo": "353/2003",
        "nazev": "Zákon o spotřebních daních",
        "typ": "specialni",
        "oblasti": ["spotřební daně"],
    },
    {
        "sbirkove_cislo": "258/2000",
        "nazev": "Zákon o ochraně veřejného zdraví",
        "typ": "specialni",
        "oblasti": ["veřejné zdraví", "hygiena"],
    },
    {
        "sbirkove_cislo": "379/2005",
        "nazev": "Zákon o opatřeních k ochraně před škodami způsobenými tabákovými výrobky",
        "typ": "specialni",
        "oblasti": ["tabák", "ochrana zdraví"],
    },
    {
        "sbirkove_cislo": "56/2001",
        "nazev": "Zákon o podmínkách provozu vozidel na pozemních komunikacích",
        "typ": "specialni",
        "oblasti": ["technická způsobilost vozidel"],
    },
    {
        "sbirkove_cislo": "168/1999",
        "nazev": "Zákon o pojištění odpovědnosti z provozu vozidla",
        "typ": "specialni",
        "oblasti": ["povinné ručení", "doprava"],
    },
    {
        "sbirkove_cislo": "13/1997",
        "nazev": "Zákon o pozemních komunikacích",
        "typ": "specialni",
        "oblasti": ["pozemní komunikace", "silniční provoz"],
    },
    {
        "sbirkove_cislo": "272/2013",
        "nazev": "Zákon o prekurzorech drog",
        "typ": "specialni",
        "oblasti": ["prekurzory drog"],
    },
    {
        "sbirkove_cislo": "206/2015",
        "nazev": "Zákon o pyrotechnických výrobcích a zacházení s nimi",
        "typ": "specialni",
        "oblasti": ["výbušniny", "pyrotechnika"],
    },
    {
        "sbirkove_cislo": "283/2021",
        "nazev": "Stavební zákon",
        "typ": "specialni",
        "oblasti": ["stavebnictví", "územní plánování"],
    },
    {
        "sbirkove_cislo": "143/2001",
        "nazev": "Zákon o ochraně hospodářské soutěže",
        "typ": "specialni",
        "oblasti": ["hospodářská soutěž"],
    },
    {
        "sbirkove_cislo": "563/1991",
        "nazev": "Zákon o účetnictví",
        "typ": "specialni",
        "oblasti": ["účetnictví"],
    },
    {
        "sbirkove_cislo": "186/2016",
        "nazev": "Zákon o hazardních hrách",
        "typ": "specialni",
        "oblasti": ["hazardní hry", "gambling"],
    },
    {
        "sbirkove_cislo": "435/2004",
        "nazev": "Zákon o zaměstnanosti",
        "typ": "specialni",
        "oblasti": ["zaměstnanost", "nelegální práce"],
    },
    {
        "sbirkove_cislo": "251/2005",
        "nazev": "Zákon o inspekci práce",
        "typ": "specialni",
        "oblasti": ["inspekce práce", "bezpečnost práce"],
    },
    {
        "sbirkove_cislo": "110/1997",
        "nazev": "Zákon o potravinách",
        "typ": "specialni",
        "oblasti": ["potraviny", "bezpečnost potravin"],
    },
    {
        "sbirkove_cislo": "378/2007",
        "nazev": "Zákon o léčivech",
        "typ": "specialni",
        "oblasti": ["léčiva", "farmacie"],
    },
    {
        "sbirkove_cislo": "372/2011",
        "nazev": "Zákon o zdravotních službách",
        "typ": "specialni",
        "oblasti": ["zdravotní služby", "zdravotnictví"],
    },
    {
        "sbirkove_cislo": "441/2003",
        "nazev": "Zákon o ochranných známkách",
        "typ": "specialni",
        "oblasti": ["ochranné známky", "duševní vlastnictví"],
    },
    {
        "sbirkove_cislo": "527/1990",
        "nazev": "Zákon o vynálezech a zlepšovacích návrzích",
        "typ": "specialni",
        "oblasti": ["patenty", "vynálezy"],
    },
    {
        "sbirkove_cislo": "412/2005",
        "nazev": "Zákon o ochraně utajovaných informací",
        "typ": "specialni",
        "oblasti": ["utajované informace", "bezpečnost"],
    },
    {
        "sbirkove_cislo": "49/1997",
        "nazev": "Zákon o civilním letectví",
        "typ": "specialni",
        "oblasti": ["letectví", "civilní letectví"],
    },
    {
        "sbirkove_cislo": "266/1994",
        "nazev": "Zákon o dráhách",
        "typ": "specialni",
        "oblasti": ["dráhy", "železniční doprava"],
    },
    {
        "sbirkove_cislo": "114/1995",
        "nazev": "Zákon o vnitrozemské plavbě",
        "typ": "specialni",
        "oblasti": ["vnitrozemská plavba", "lodní doprava"],
    },
    {
        "sbirkove_cislo": "263/2016",
        "nazev": "Atomový zákon",
        "typ": "specialni",
        "oblasti": ["jaderná energie", "radiační ochrana"],
    },
    {
        "sbirkove_cislo": "134/2016",
        "nazev": "Zákon o zadávání veřejných zakázek",
        "typ": "specialni",
        "oblasti": ["veřejné zakázky"],
    },
    {
        "sbirkove_cislo": "359/1999",
        "nazev": "Zákon o sociálně-právní ochraně dětí",
        "typ": "specialni",
        "oblasti": ["ochrana dětí", "sociální péče"],
    },
]
